server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/dbpurchase?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

spring.sql.init.mode=never
spring.jpa.show-sql=true


# ==============================
# Material Service - Port 8088
# ==============================

MaterialServiceConsumer.serviceURL=http://localhost:8088/material


# Material Category APIs

MaterialCategoryConsumer.apiURL=/controller/getMaterialCategories
MaterialCategoryConsumer.apiURLForById=/controller/getMaterialCategoryById/


# Material Type APIs
MaterialTypeConsumer.serviceURL=http://localhost:8088
MaterialTypeConsumer.apiURL=/type/controller/getTypeDetails
MaterialTypeConsumer.apiURLByCategoryId=/type/controller/getTypeDetailsByCategoryId/


# Unit APIs
UnitServiceConsumer.serviceURL=http://localhost:8088
UnitServiceConsumer.apiURL=/unit/controller/getUnitDetails
UnitServiceConsumer.apiURLByCategoryId=/unit/controller/getUnitsByCategoryId/


# ==============================
# Vendor Service - Port 8087
# ==============================

VendorServiceConsumer.serviceURL=http://localhost:8087/vendor
VendorServiceConsumer.apiURL=/controller/getVendors